development: &default
  adapter: postgresql
  encoding: unicode
  database: planner_development
  pool: 5
  username: postgres
  password:
  host: <%= (ENV['DB_HOST'] || 'localhost').to_json %>

test:
  <<: *default
  database: planner_test
  pool: 5
